[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39", features = ["full"] }
dashmap = "5.5"
futures = "0.3"
dotenvy = "0.15"
chrono = { version = "0.4", default-features = true }